### ISSUE TITLE
Generate On/off and Dyskinesia variables for syn20822276

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#10]
Generate `on_off` and `dyskinesia` variables from `medication_state` as follows:

`medication_state` = {1, 6} => `on_off` & `dyskinesia` = NA
`medication_state` = 2  => `on_off` = 0 & `dyskinesia` = 0
`medication_state` = 3  => `on_off` = 1 & `dyskinesia` = 0
`medication_state` = 4  => `on_off` = 1 & `dyskinesia` = 1
`medication_state` = 5  => `on_off` = 0 & `dyskinesia` = 2

in syn20822276.

**Comment by philerooski** [comment]
done
