### ISSUE TITLE
Explore low activity minimum for features..

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#12]

**Comment by sieberts** [comment]
@nshawen to provide measurement_ids of bad segments using various threshhold critiera to @sieberts . Then Solly will look at the effect of throwing out these measurement_ids on sample size threshholding.

**Comment by nshawen** [comment]
@sieberts I added a file, 'VarianceThresholdResults_CIS-PD.csv', with the measurement_ids, counts of low variance windows, and length of the longest streak of normal variance windows. The file is in the Extracted Features/CIS-PD folder.

Hopefully this gives us enough to play around with to find the right balance, but let me know if you there is anything else I can add. I'll start working on doing the same with the REAL-PD data and update once that's available.

**Comment by sieberts** [comment]
Thanks @nshawen! Just to make sure I'm interpreting this correctly, the column "Highest # of Consecutive Above-Threshold Windows" is the longest stretch of above threshold time blocks for that measurement_id?

**Comment by sieberts** [comment]
Also, I think you may have inadvertently filtered some measurement_ids with missing values for On/Off, but scores for Dyskinesia and Tremor. I haven't filtered these from my analysis. Those measurement_ids are saved in syn21075710.

**Comment by nshawen** [comment]
Yes, you're right about that column. I also just updated the file to add in those missing measurement_ids.

**Comment by nshawen** [comment]
The REAL-PD results are available now, as well as two Excel files (one for each study) with threshold values and some details on getting the comparable values from my feature files.

**Comment by sieberts** [comment]
Moving forward with threshold of 4 for Consecutive Above Threshold Windows.
