### ISSUE TITLE
Run model(s) on Solly's training/test splits

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#14]
https://www.synapse.org/#!Synapse:syn21036470

**Comment by sieberts** [comment]
@atm15 when you've uploaded to Synapse, please comment with the Synapse ID of the your file stats and close issue.

**Comment by atm15** [comment]
@sieberts I'll do that once I fix the issue you just found with my .csvs

**Comment by atm15** [comment]
https://www.synapse.org/#!Synapse:syn21136864
