### ISSUE TITLE
Curate CIS-PD Data for release

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#21]
1. Upload to BC for full release. Timeline for the latter is 1st week of December. 
2. Create a version in Synapse for use by Evidation team in their hackathon. Timeline is prior to Dec 13th hackathon.

**Comment by sieberts** [comment]
Training/test/ancillary data lists are here: https://www.synapse.org/#!Synapse:syn21291569

Synapse version should be saved to the Staging project: https://www.synapse.org/#!Synapse:syn20825170

**Comment by philerooski** [comment]
1 -- Store to BC only the training and ancillary datasets for now. Generate separate manifests for training and ancillary datasets.
2 -- Store a soft copy of the CIS PD sensor data table in staging as well

**Comment by philerooski** [comment]
2. ✅ 

Sensor data: https://www.synapse.org/#!Synapse:syn21302049/tables/
Labels, demographics, surveys: https://www.synapse.org/#!Synapse:syn21302037

**Comment by philerooski** [comment]
@sieberts Will default permissions on the above files/tables in the staging project be sufficient for Evidation to access them or should we create a new team?

**Comment by sieberts** [comment]
@philerooski creating a team for them would be the easiest, I think.

**Comment by philerooski** [comment]
I've created a team and invited you so that you can be a team manager as well.

For the upload to BC, I have a folder structure like this:

```
cis-pd
├── CIS-PD_Ancillary_Data_IDs_Labels.csv
├── CIS-PD_Demographics.csv
├── CIS-PD_Test_Data_IDs.csv
├── CIS-PD_Training_Data_IDs_Labels.csv
├── CIS-PD_UPDRS_Part1_2_4.csv
├── CIS-PD_UPDRS_Part3.csv
├── ancillary_data [352 entries exceeds filelimit, not opening dir]
├── testing_data [618 entries exceeds filelimit, not opening dir]
└── training_data [1858 entries exceeds filelimit, not opening dir]
```
where the sensor measurement data in the *_data directories  are named like measurement_id.csv. I should _not_ upload the testing_data directory just yet, correct?

**Comment by sieberts** [comment]
For BC that is correct, do not upload any test data right now. This includes CIS-PD_Test_Data_IDs.csv. 

If we can use folder structures, it might be clearer to put the Ancillary and Training IDs/Labels files in a folder called something like Data_Labels, and put the Demographics and UPDRS files in a folder called Clinical_Data, but if it is too late to change, that's fine.

**Comment by philerooski** [comment]
I see 370 measurement ids that are neither in training, testing, nor ancillary data sets. Are these the zero variance measurements?

**Comment by sieberts** [comment]
They would either be zero variance, or have been filtered by missing phenotypes, or individuals who have not been released. If they haven't been explicitly listed, they don't need to be released.
