### ISSUE TITLE
Curate REAL-PD Data for release

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#25]
See instructions for CIS here: https://github.com/Sage-Bionetworks/beat-pd/issues/21

REAL-PD data/lists are here: syn21291570

Also, please copy the Data dictionary (syn21344783) to both copies (Synapse and BC).

**Comment by philerooski** [comment]
I've just now been able to copy the data dictionary over as well.

**Comment by sieberts** [comment]
I don't see it in the Synapse project, unless I missed it. This is necessary for Evidation's Hackathon.

**Comment by philerooski** [comment]
Synapse? Besides the data dictionary, I had initially thought this was only for the BC transfer.

Just to double-check. Evidation will be hacking on the REAL PD data as well? There is nothing REAL-PD related in Staging yet.

**Comment by philerooski** [comment]
Oh. It was not clear to me that you expect REAL-PD and CIS-PD predictions of a single phenotype/trait to be submitted together. I remember we had different submission queues for different datasets in the previous challenge.

**Comment by sieberts** [comment]
For the last challenge, the data sets had different trait/phenotypes and couldn't be harmonized, which is why there were separate subchallenges by dataset. For this challenge, the trait/phenotypes are available for both datasets. So, they need all the data for the Hackathon on Friday.
