### ISSUE TITLE
Instructions for Accessing the Data (Evidation Hackathon)

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#28]
Please create instructions for accessing the data for the Synapse/Evidation version here: https://www.synapse.org/#!Synapse:syn20825170/wiki/599615

**Comment by philerooski** [comment]
Remind me the deadline for this?

**Comment by sieberts** [comment]
Thursday. Their Hackathon runs starting midnight on Friday.

**Comment by philerooski** [comment]
Include code for download REAL-PD data as well

**Comment by sieberts** [comment]
@philerooski Can you put some comments in your code or some text following the code blocks detailing the expected output, drawing attention to the file naming issue? I've already written a note about being careful with the filenames. Also, there's one place on the page I've tagged which needs more detail from you.
