### ISSUE TITLE
Implement end-of-round reporting on most recent submissions

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/beat-pd#34]
* At the end of each round, we report to participants their rank relative to the other participants as well as whether they did better than the null model.
* This should only consider the most recently submitted submission for each team (if there is a team submission) or each individual (if the participant has decided to submit as an individual instead).
*  Rank is determined by the square root of the weighted MSE, though we do not report this directly to the submitter.

**Comment by sieberts** [comment]
Lower scores weighted MSE = better (lower rank).
