### ISSUE TITLE
Double check Tremor values for hbv074 (REAL-PD).

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#9]
In the Synapse table of scores (https://www.synapse.org/#!Synapse:syn20822276/tables/) 
there are 3 tremor values of '5'
which are not present in the curated file (https://www.synapse.org/#!Synapse:syn20555354). 

Please check source on this and follow up with @sieberts as necessary.

**Comment by philerooski** [comment]
It took a long time for me to dig to the source of this problem, and it seems to be a mixture of nothing is wrong / a bug with synapser or the Synapse platform.

As an example, look at the very first row of the table. The diary_start_timestamp reads 02/24/2018 9:00 PM. You might think this is UTC, but _no_, surprisingly this is displayed in Pacific Time. If I look at that same value in R I get:

```
> diary_raw$diary_start_timestamp[[1]]
[1] "2018-02-25 06:00:00 CET"
```

Which in UTC is
```
> diary_raw$diary_start_timestamp[[1]] %>% lubridate::with_tz("UTC")
[1] "2018-02-25 05:00:00 UTC"
```

And in PT is:
```
> diary_raw$diary_start_timestamp[[1]] %>% lubridate::with_tz("America/Los_Angeles")
[1] "2018-02-24 21:00:00 PST"
```

So if you download the table and change the datetime values to the correct timezone, they will match what you see in the source files.

**Comment by sieberts** [comment]
Sorry, but how does this affect the values for the tremor score? Your comments appear to be based on the timestamps, not the phenotype scores.

**Comment by philerooski** [comment]
Ah, I was so concerned with my own issue I forgot to address the actual issue.

After some more digging it seems that you are linking to the wrong source file. That file (https://www.synapse.org/#!Synapse:syn20555354) is for measurements taken March 1, 2018 but the tremor measurements with value 5 are all from February 5, 2018. If you look at the source file I used to curate the table (https://www.synapse.org/#!Synapse:syn20769648) you can see the 5s.

![image](https://user-images.githubusercontent.com/2773709/66947175-471c8700-f007-11e9-8a6f-af85273603ef.png)
(I did some munging on the source to make this easier to show).

I actually couldn't find a "diary.hbv074"-esque file in _those_ source files  (https://www.synapse.org/#!Synapse:syn20555237) for February 5. Those records only exist in the cleaner version of the scores.

**Comment by sieberts** [comment]
The Hyve only generated a single diary file per individual, meaning that if the 2/25 entries don't exist in the curated file, they've probably excluded the entries for some reason. I guess I'll follow up with the Hyve on this and cc you @philerooski .

**Comment by sieberts** [comment]
The error appears to be on the Hyve side. Closing this issue.

**Comment by sieberts** [comment]
P.S. 5 is a valid entry for tremor. It means "severe".
